name: CI - client - android

on: workflow_dispatch

jobs:
  build:
    environment: build

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - run: sh ./ci-setup.sh
        working-directory: ./
        env:
          _APPENV_TS: ${{ secrets._APPENV_TS }}
          _FIREBASERC: ${{ secrets._FIREBASERC }}
          _ASSETLINKS_JSON: ${{ secrets._ASSETLINKS_JSON }}
          _GOOGLE_SERVICES_JSON: ${{ secrets._GOOGLE_SERVICES_JSON }}
          _ANDROID_CUSTOM_PROPS: ${{ secrets._ANDROID_CUSTOM_PROPS }}

      - uses: actions/setup-java@v1
        with:
          java-version: '1.8'

      - uses: actions/setup-node@v2
        with:
          node-version: '14'
          cache: 'npm'

      - run: npm install
        working-directory: ./client

      - run: rm -rf ./client/android

      - run: npx cap add android
        working-directory: ./client

      - run: npm run build.android
        working-directory: ./client

      - run: ./gradlew assembleDebug
        working-directory: ./client/android
