name: CI - client - android

on: workflow_dispatch

jobs:
  build:
    environment: build

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./client

    steps:
      - uses: actions/checkout@v2

      - name: ci setup
        run: sh ./ci-setup.sh
        working-directory: ./
        env:
          _APPENV_TS: ${{ secrets._APPENV_TS }}
          _FIREBASERC: ${{ secrets._FIREBASERC }}
          _ASSETLINKS_JSON: ${{ secrets._ASSETLINKS_JSON }}

      - uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: build
        run: npm run build.cap
